# Default values for flower
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: airflow-helm
  tag: 1.8.1-1.6.2
  pullPolicy: IfNotPresent
service:
  name: flower
  type: NodePort
  externalPort: 32081
  internalPort: 5555
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

